# Generated by Django 3.1.2 on 2020-10-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_auto_20201009_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Circle admins can update the circles data and manage its members', verbose_name='circle admin'),
        ),
    ]
