# Generated by Django 3.1.2 on 2020-10-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='offeded_in',
            new_name='offered_in',
        ),
    ]
