# Generated by Django 3.1.2 on 2020-10-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20201010_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Used for disabling the ride or marking it has finished', verbose_name='active status'),
        ),
    ]
